"""Adding_query_schema

Revision ID: 2cefce99b2b9
Revises: 4ad3a1c71da2
Create Date: 2026-06-29 18:13:14.166111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cefce99b2b9'
down_revision: Union[str, None] = '4ad3a1c71da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
