"""add_user_profile_table

Revision ID: 4ad3a1c71da2
Revises: fc5158d08113
Create Date: 2026-06-28 18:35:01.148696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad3a1c71da2'
down_revision: Union[str, None] = 'fc5158d08113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goals', sa.JSON(), nullable=False),
    sa.Column('current_challenges', sa.JSON(), nullable=False),
    sa.Column('personality_traits', sa.JSON(), nullable=False),
    sa.Column('environment_constraints', sa.JSON(), nullable=False),
    sa.Column('existing_habits', sa.JSON(), nullable=False),
    sa.Column('areas_to_improve', sa.JSON(), nullable=False),
    sa.Column('preferred_learning_style', sa.String(length=30), nullable=True),
    sa.Column('available_time_per_week_hours', sa.Float(), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
