"""add_processing_columns_to_documents

Revision ID: 843a8c88fdff
Revises: 6052f75a5e8d
Create Date: 2026-06-23 19:17:09.723127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '843a8c88fdff'
down_revision: Union[str, None] = '6052f75a5e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('total_pages', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('total_chunks', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('processing_status', sa.String(length=20), nullable=False, server_default='pending'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processing_status')
    op.drop_column('documents', 'total_chunks')
    op.drop_column('documents', 'total_pages')
    # ### end Alembic commands ###
