"""updated_query_schema_and_user_profile_schema

Revision ID: d90c0f67f4a0
Revises: 2cefce99b2b9
Create Date: 2026-06-29 19:09:14.390516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd90c0f67f4a0'
down_revision: Union[str, None] = '2cefce99b2b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
